import { AccessServiceProxy, AdminServiceProxy, AuthServiceProxy, CabDriverServiceProxy, ClerkServiceProxy, 
  DashBoardServiceProxy, 
  DivisionServiceProxy, FeeParticularServiceProxy, FeePaymentServiceProxy, FeeWavierTypeServiceProxy, GradeDivisionMatrixServiceProxy, GradeServiceProxy, HomeworkServiceProxy, MasterServiceProxy, 
  NoticeServiceProxy, 
  ParentServiceProxy, SchoolServiceProxy, StudentAttendanceServiceProxy, StudentServiceProxy,
    StudentDocumentServiceProxy,
  TeacherServiceProxy, 
  ClassTimeTableServiceProxy,
  StudentAttendanceReportServiceProxy,
  CommonAppServiceProxy,
  StudentProfileServiceProxy,
  TeacherProfileServiceProxy,
  SchoolCalendarServiceProxy,
  ParentAppServiceProxy,
  CabDriverAppServiceProxy,
  GalleryServiceProxy,
  } from "./services/school-api-service";

export const API_PROVIDERS = [
    { provide: AuthServiceProxy, useClass: AuthServiceProxy },
    { provide: SchoolServiceProxy, useClass: SchoolServiceProxy },
    { provide: MasterServiceProxy, useClass: MasterServiceProxy },
    { provide: StudentServiceProxy, useClass: StudentServiceProxy },
    { provide: ParentServiceProxy, useClass: ParentServiceProxy },
    { provide: GradeServiceProxy,useClass: GradeServiceProxy },
    { provide: DivisionServiceProxy,useClass: DivisionServiceProxy },
    { provide: ClerkServiceProxy,useClass: ClerkServiceProxy },
    { provide: AdminServiceProxy,useClass: AdminServiceProxy },
    { provide: TeacherServiceProxy,useClass: TeacherServiceProxy },
    { provide: CabDriverServiceProxy,useClass: CabDriverServiceProxy },
    { provide: AccessServiceProxy,useClass: AccessServiceProxy },
    { provide: GradeDivisionMatrixServiceProxy,useClass: GradeDivisionMatrixServiceProxy },
    { provide: FeePaymentServiceProxy,useClass: FeePaymentServiceProxy },
    { provide: FeeParticularServiceProxy,useClass: FeeParticularServiceProxy },
    { provide: FeeWavierTypeServiceProxy,useClass: FeeWavierTypeServiceProxy },
    { provide: StudentAttendanceServiceProxy,useClass: StudentAttendanceServiceProxy },
    { provide: HomeworkServiceProxy,useClass: HomeworkServiceProxy },
    { provide: DashBoardServiceProxy, useClass: DashBoardServiceProxy},
    {provide:NoticeServiceProxy,useClass:NoticeServiceProxy},
    { provide: StudentDocumentServiceProxy,useClass:StudentDocumentServiceProxy},
    {provide:ClassTimeTableServiceProxy,useClass:ClassTimeTableServiceProxy},
    {provide:StudentAttendanceReportServiceProxy,useClass:StudentAttendanceReportServiceProxy},
    {provide:CommonAppServiceProxy,useClass:CommonAppServiceProxy},
    {provide:StudentProfileServiceProxy,useClass:StudentProfileServiceProxy},
    {provide:TeacherProfileServiceProxy,useClass:TeacherProfileServiceProxy},
    {provide:SchoolCalendarServiceProxy,useClass:SchoolCalendarServiceProxy},
    {provide:ParentAppServiceProxy,useClass:ParentAppServiceProxy},
    {provide:CabDriverAppServiceProxy,useClass:CabDriverAppServiceProxy},
    {provide:GalleryServiceProxy,useClass:GalleryServiceProxy},

  ];
  