import { ClassAttendanceMisssingReportComponent } from "./modules/dashboard/class-attendance-misssing-report/class-attendance-misssing-report.component";
import { AccessServiceProxy, AdminServiceProxy, AuthServiceProxy, CabDriverServiceProxy, ClerkServiceProxy, 
  DashBoardServiceProxy, 
  DivisionServiceProxy, FeeParticularServiceProxy, FeePaymentServiceProxy, FeeWavierTypeServiceProxy, GradeDivisionMatrixServiceProxy, GradeServiceProxy, HomeworkServiceProxy, MasterServiceProxy, 
  NoticeServiceProxy, 
  ParentServiceProxy, SchoolServiceProxy, StudentAttendanceServiceProxy, StudentServiceProxy,
    StudentDocumentServiceProxy,
  TeacherServiceProxy, 
  ClassTimeTableServiceProxy,
  StudentAttendanceReportServiceProxy,
  StudentAttendanceDateWiseServiceProxy,
  TeacherGradeDivisionMappingServiceProxy,
  PromoteServiceProxy,
  StudentsImportServiceProxy,
  SchoolHolidayServiceProxy,
  WeeklyDayOffServiceProxy,
  SchoolEventServiceProxy,
  StudentExportServiceProxy,
  SchoolCalendarServiceProxy,
  PaymentAnalyticsExportServiceProxy,
TeacherExportServiceProxy,
  SubjectMappingServiceProxy,
  TeacherSubjectMappingServiceProxy,
  PaymentAnalyticsServiceProxy,
  SubjectMasterServiceProxy,
  ClassTeacherDataServiceProxy,
  SchoolVacationServiceProxy,
  SubjectImportServiceProxy,
  TeachingLoadAnalysisServiceProxy,
  ClassAttendanceMissingReportServiceProxy,
  SchoolMonthEventServiceProxy,
  AdhocFeePaymentServiceProxy,
  AdhocParticularMasterServiceProxy,
  TeacherOneDayLectureServiceProxy,
  TeacherCountPerSubjectAnalyzerServiceProxy,
  TransportServiceProxy,
  SurveyServiceProxy,
  ClassWiseTeacherAndStudentServiceProxy,
  TransportFeePaymentServiceProxy,
  TransportPaymentAnalyticsServiceProxy,
  TransportPaymentAnalyticsExportServiceProxy,
  StudentKitFeePaymentServiceProxy,
  StudentKitAnalyticsPaymentAnalyticsServiceProxy,
  StudentKitPaymentAnalyticsExportServiceProxy,
  StudentReportServiceProxy,
  GalleryServiceProxy,
  CBSE_ExamObjectServiceProxy,
  CBSE_ExamResultServiceProxy,
  CBSE_ExamReportCardServiceProxy,
  StudentEnquiryServiceProxy,
  BulkAttendanceUpdateServiceProxy,
  RegistrationFeePaymentServiceProxy,
  CBSE_AcademicAssessmentReportServiceProxy,
} from "./services/school-api-service";
 




export const API_PROVIDERS = [
    { provide: AuthServiceProxy, useClass: AuthServiceProxy },
    { provide: SchoolServiceProxy, useClass: SchoolServiceProxy },
    { provide: MasterServiceProxy, useClass: MasterServiceProxy },
    { provide: StudentServiceProxy, useClass: StudentServiceProxy },
    { provide: ParentServiceProxy, useClass: ParentServiceProxy },
    { provide: GradeServiceProxy,useClass: GradeServiceProxy },
    { provide: DivisionServiceProxy,useClass: DivisionServiceProxy },
    { provide: ClerkServiceProxy,useClass: ClerkServiceProxy },
    { provide: AdminServiceProxy,useClass: AdminServiceProxy },
    { provide: TeacherServiceProxy,useClass: TeacherServiceProxy },
    { provide: CabDriverServiceProxy,useClass: CabDriverServiceProxy },
    { provide: AccessServiceProxy,useClass: AccessServiceProxy },
    { provide: GradeDivisionMatrixServiceProxy,useClass: GradeDivisionMatrixServiceProxy },
    { provide: FeePaymentServiceProxy,useClass: FeePaymentServiceProxy },
    { provide: StudentKitFeePaymentServiceProxy,useClass: StudentKitFeePaymentServiceProxy },
    { provide: TransportFeePaymentServiceProxy,useClass: TransportFeePaymentServiceProxy },
    { provide: FeeParticularServiceProxy,useClass: FeeParticularServiceProxy },
    { provide: FeeWavierTypeServiceProxy,useClass: FeeWavierTypeServiceProxy },
    { provide: StudentAttendanceServiceProxy,useClass: StudentAttendanceServiceProxy },
    { provide: HomeworkServiceProxy,useClass: HomeworkServiceProxy },
    { provide: DashBoardServiceProxy, useClass: DashBoardServiceProxy},
    {provide:NoticeServiceProxy,useClass:NoticeServiceProxy},
    { provide: StudentDocumentServiceProxy,useClass:StudentDocumentServiceProxy},
    {provide:ClassTimeTableServiceProxy,useClass:ClassTimeTableServiceProxy},
    {provide:StudentAttendanceReportServiceProxy,useClass:StudentAttendanceReportServiceProxy},
    {provide:StudentAttendanceDateWiseServiceProxy,useClass:StudentAttendanceDateWiseServiceProxy},
    {provide:PromoteServiceProxy,useClass:PromoteServiceProxy},
    {provide:ClassTimeTableServiceProxy,useClass:ClassTimeTableServiceProxy},
    {provide: StudentsImportServiceProxy,useClass:StudentsImportServiceProxy},
    {provide:SchoolHolidayServiceProxy,useClass:SchoolHolidayServiceProxy},
    {provide:StudentAttendanceDateWiseServiceProxy,useClass:StudentAttendanceDateWiseServiceProxy},
    {provide:WeeklyDayOffServiceProxy,useClass:WeeklyDayOffServiceProxy},
    {provide:StudentAttendanceDateWiseServiceProxy,useClass:StudentAttendanceDateWiseServiceProxy},
    {provide:SchoolEventServiceProxy,useClass:SchoolEventServiceProxy},
    {provide:StudentExportServiceProxy,useClass:StudentExportServiceProxy},
    {provide:PaymentAnalyticsServiceProxy,useClass:PaymentAnalyticsServiceProxy},
    {provide:StudentAttendanceDateWiseServiceProxy,useClass:StudentAttendanceDateWiseServiceProxy},
    {provide:TeacherGradeDivisionMappingServiceProxy,useClass:TeacherGradeDivisionMappingServiceProxy},
    {provide:SubjectMasterServiceProxy,useClass:SubjectMasterServiceProxy},
    {provide:SchoolCalendarServiceProxy,useClass:SchoolCalendarServiceProxy},
    {provide:PaymentAnalyticsExportServiceProxy,useClass: PaymentAnalyticsExportServiceProxy},

    {provide:TeacherExportServiceProxy,useClass:TeacherExportServiceProxy},

    {provide:SubjectMappingServiceProxy,useclass:SubjectMappingServiceProxy},
    {provide:TeacherSubjectMappingServiceProxy, useclass:TeacherSubjectMappingServiceProxy},
    {provide:ClassTeacherDataServiceProxy, useclass:ClassTeacherDataServiceProxy},
    {provide:SchoolVacationServiceProxy, useclass:SchoolVacationServiceProxy},
    {provide:SubjectImportServiceProxy, useclass:SubjectImportServiceProxy},
    {provide:TeachingLoadAnalysisServiceProxy, useclass:TeachingLoadAnalysisServiceProxy},
    {provide:ClassAttendanceMissingReportServiceProxy, useclass:ClassAttendanceMissingReportServiceProxy},
    {provide:SchoolMonthEventServiceProxy, useclass:SchoolMonthEventServiceProxy},
    {provide:AdhocFeePaymentServiceProxy, useclass:AdhocFeePaymentServiceProxy},
    {provide:AdhocParticularMasterServiceProxy, useclass:AdhocParticularMasterServiceProxy},
    {provide:TeacherOneDayLectureServiceProxy, useclass:TeacherOneDayLectureServiceProxy},
    {provide:TeacherCountPerSubjectAnalyzerServiceProxy, useclass:TeacherCountPerSubjectAnalyzerServiceProxy},
    {provide:TransportServiceProxy, useclass:TransportServiceProxy},
    {provide:SurveyServiceProxy, useclass:SurveyServiceProxy},
    {provide:ClassWiseTeacherAndStudentServiceProxy, useclass:ClassWiseTeacherAndStudentServiceProxy},
    {provide: TransportPaymentAnalyticsServiceProxy, useclass: TransportPaymentAnalyticsServiceProxy},
    {provide: TransportPaymentAnalyticsExportServiceProxy, useclass: TransportPaymentAnalyticsExportServiceProxy},
    {provide: StudentKitAnalyticsPaymentAnalyticsServiceProxy, useclass: StudentKitAnalyticsPaymentAnalyticsServiceProxy},
    {provide: StudentKitPaymentAnalyticsExportServiceProxy, useclass: StudentKitPaymentAnalyticsExportServiceProxy},
    {provide: StudentReportServiceProxy, useclass: StudentReportServiceProxy},
    {provide: GalleryServiceProxy, useclass: GalleryServiceProxy},
    {provide: CBSE_ExamObjectServiceProxy, useclass: CBSE_ExamObjectServiceProxy},
    {provide: CBSE_ExamResultServiceProxy, useclass: CBSE_ExamResultServiceProxy},
    {provide: CBSE_ExamReportCardServiceProxy, useclass: CBSE_ExamReportCardServiceProxy},
    {provide: StudentEnquiryServiceProxy, useclass: StudentEnquiryServiceProxy},
    {provide: BulkAttendanceUpdateServiceProxy, useclass: BulkAttendanceUpdateServiceProxy},
    {provide: RegistrationFeePaymentServiceProxy, useclass: RegistrationFeePaymentServiceProxy},
    {provide: CBSE_AcademicAssessmentReportServiceProxy, useclass: CBSE_AcademicAssessmentReportServiceProxy},

  ];
  
  